"use client";

import { useState } from "react";
import { Sparkles } from "lucide-react";
import type { AiSettings } from "@/lib/sim/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type StoredAiSettings = NonNullable<AiSettings>;

interface CreateSimulationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (name: string, description: string) => Promise<void>;
}

function getStoredAiSettings(): StoredAiSettings | null {
  if (typeof window === "undefined") return null;

  const provider = window.localStorage.getItem("sim-provider");
  const apiKey = window.localStorage.getItem("sim-api-key");
  const model = window.localStorage.getItem("sim-model");

  if (!provider || !apiKey || !model) {
    return null;
  }

  return {
    provider: provider as StoredAiSettings["provider"],
    apiKey,
    model,
  };
}

export function CreateSimulationModal({
  isOpen,
  onClose,
  onSubmit,
}: CreateSimulationModalProps) {
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGeneratingDescription, setIsGeneratingDescription] = useState(false);
  const [generationError, setGenerationError] = useState<string | null>(null);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!name.trim()) return;

    setIsSubmitting(true);
    try {
      await onSubmit(name.trim(), description.trim());
      setName("");
      setDescription("");
      setGenerationError(null);
      onClose();
    } catch (error) {
      console.error("Failed to create simulation:", error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleAutoGenerateDescription = async () => {
    const aiSettings = getStoredAiSettings();
    if (!aiSettings) {
      setGenerationError("Add your AI provider and API key in workspace settings first.");
      return;
    }

    setIsGeneratingDescription(true);
    setGenerationError(null);

    try {
      const response = await fetch("/api/projects/generate-description", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, aiSettings }),
      });
      const data = await response.json();

      if (!response.ok || !data.description) {
        throw new Error(data.error || "Description generation failed.");
      }

      setDescription(data.description);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Description generation failed.";
      setGenerationError(message);
    } finally {
      setIsGeneratingDescription(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="overflow-hidden bg-[var(--bg-dock)]">
        <DialogHeader className="border-b border-[var(--border-subtle)] bg-[var(--bg-panel)]">
          <Badge variant="accent" className="w-fit">New simulation</Badge>
          <DialogTitle className="text-[2rem] tracking-[-0.05em]">Forge a fresh timeline</DialogTitle>
          <DialogDescription className="max-w-xl">
            Start with a clear title, generate an editable high-stakes premise, and move directly
            into guided setup so the first branch has structure before it has spectacle.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-6 p-6">
          <section className="space-y-2">
            <label htmlFor="sim-name" className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--text-muted)]">
              Title
            </label>
            <Input
              id="sim-name"
              type="text"
              placeholder="e.g. Fracture at the Glass Strait"
              value={name}
              onChange={(event) => setName(event.target.value)}
              autoFocus
              required
            />
          </section>

          <section className="space-y-2">
            <div className="flex items-center justify-between gap-3">
              <label htmlFor="sim-desc" className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--text-muted)]">
                Scenario premise
              </label>
              <Button
                variant="ghost"
                size="sm"
                type="button"
                onClick={handleAutoGenerateDescription}
                disabled={!name.trim() || isSubmitting || isGeneratingDescription}
              >
                <Sparkles className="h-3.5 w-3.5" />
                {isGeneratingDescription ? "Generating..." : "Generate with AI"}
              </Button>
            </div>
            <Textarea
              id="sim-desc"
              placeholder="Describe the trigger, the parties under tension, and why the system is likely to escalate."
              value={description}
              onChange={(event) => setDescription(event.target.value)}
              rows={4}
            />
            {generationError ? <p className="text-sm text-[#f2a5a5]">{generationError}</p> : null}
          </section>

          <section className="grid gap-3 md:grid-cols-2">
            <div className="rounded-lg border border-[var(--border-subtle)] bg-[var(--bg-panel)] p-4">
              <div className="mb-2 text-sm font-semibold text-[var(--text-primary)]">Blank world first</div>
              <p className="text-sm leading-6 text-[var(--text-secondary)]">
                No demo seed. You will shape the first campaign board in guided setup.
              </p>
            </div>
            <div className="rounded-lg border border-[var(--border-subtle)] bg-[var(--bg-panel)] p-4">
              <div className="mb-2 text-sm font-semibold text-[var(--text-primary)]">AI suggests only</div>
              <p className="text-sm leading-6 text-[var(--text-secondary)]">
                Factions, fronts, routes, and the inciting rupture remain editable before launch.
              </p>
            </div>
          </section>

          <DialogFooter className="border-t-0 p-0 pt-2">
            <Button variant="ghost" onClick={onClose} type="button" disabled={isSubmitting}>
              Cancel
            </Button>
            <Button variant="primary" type="submit" disabled={isSubmitting || !name.trim()}>
              {isSubmitting ? "Forging..." : "Open Campaign Setup"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
