async function run() {
  const API_BASE = "http://localhost:3000";

  async function cmd(branchId, currentTick, payload) {
    const response = await fetch(`${API_BASE}/api/sim`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        branchId,
        currentTick,
        ...payload
      })
    });
    
    const text = await response.text();
    let result;
    try {
      result = JSON.parse(text);
    } catch (e) {
      throw new Error(`Failed to parse API response: ${response.status} ${text.substring(0, 50)}`);
    }

    if (!response.ok || result.error) throw new Error(`Command failed: ${result.error || response.statusText}`);
    return result;
  }

  console.log("Fetching branches...");
  const res = await fetch(`${API_BASE}/api/branches?projectId=proj-demo`);
  const data = await res.json();
  const defaultBranch = data.branches[0];
  if (!defaultBranch) throw new Error("No default branch found");
  
  let currentBranchId = defaultBranch.id;
  let currentTick = defaultBranch.latestState?.tick || 0;

  console.log("Branch:", currentBranchId, "Tick:", currentTick);

  console.log("1. Creating 'Edison vs Tesla E2E' Branch...");
  const dev = await cmd(currentBranchId, currentTick, { type: "createBranch", name: "Edison vs Tesla E2E", summary: "Testing concurrency" });
  if (dev.branch) {
    currentBranchId = dev.branch.id;
    currentTick = dev.branch.currentTick;
  }
  
  console.log("2. Spawning Thomas Edison...");
  const resEdison = await cmd(currentBranchId, currentTick, { type: "createCampaignNode", name: "Thomas Edison", kind: "agent", x: -200, y: 0 });
  currentTick = resEdison.worldState.tick;
  
  console.log("3. Spawning Nikola Tesla...");
  const resTesla = await cmd(currentBranchId, currentTick, { type: "createCampaignNode", name: "Nikola Tesla", kind: "agent", x: 200, y: 0 });
  currentTick = resTesla.worldState.tick;
  
  console.log("4. Spawning War of the Currents Front...");
  const resFront = await cmd(currentBranchId, currentTick, { type: "createCampaignNode", name: "War of the Currents", kind: "front", x: 0, y: -200 });
  const frontNode = resFront.worldState.campaignNodes[resFront.worldState.campaignNodes.length - 1];
  currentTick = resFront.worldState.tick;

  console.log("5. Injecting Event...");
  const injectRes = await cmd(currentBranchId, currentTick, {
    type: "injectEvent",
    event: { 
      summary: "Edison electrically executes an elephant using AC power to demonstrate its lethal danger.",
      sourceId: frontNode.id 
    }
  });
  currentTick = injectRes.worldState.tick;
  console.log("Event Injected successfully at tick", currentTick);

  console.log("6. Fast forwarding 2 ticks to resolve consequence proposals API...");
  const ffRes = await cmd(currentBranchId, currentTick, { type: "fastForward", ticks: 2, aiSettings: { consequenceGeneration: true } });
  
  console.log("========= TEST COMPLETE =========");
  console.log("Latest Events Generated by Engine:");
  ffRes.worldState.events.slice(-3).forEach(e => {
    console.log(`- [Tick ${e.tick}] [${e.type}] ${e.description}`);
  });
}

run().catch(err => {
  console.error("TEST FAILED:", err);
  process.exit(1);
});
