import { PrismaStore } from "../lib/server/db-store";
import { SimController } from "../lib/server/sim-controller";
import { DEMO_PROJECT_ID } from "../lib/server/store";

async function run() {
  const store = new PrismaStore();
  const controller = new SimController(store);

  console.log("Fetching branches...");
  const branches = await store.listBranches(DEMO_PROJECT_ID);
  const defaultBranch = branches[0];
  if (!defaultBranch) {
    throw new Error("No default branch exists.");
  }

  let currentBranchId = defaultBranch.id;
  let currentTick = defaultBranch.currentTick || 0;

  async function cmd(payload: any) {
    const response = await controller.execute({
      branchId: currentBranchId,
      currentTick,
      ...payload
    });
    
    if (response.error || response.status >= 300) {
      throw new Error(`Command failed: ${response.error || response.status}`);
    }

    if (response.data?.branch) {
      currentBranchId = response.data.branch.id;
      currentTick = response.data.branch.currentTick;
    }
    return response.data;
  }

  console.log("1. Creating 'Edison vs Tesla Internal' Branch...");
  const dev = await cmd({ type: "createBranch", name: "Edison vs Tesla E2E", summary: "Testing E2E Controller" });
  if (dev.branch) {
    currentBranchId = dev.branch.id;
    currentTick = dev.branch.currentTick;
  }
  
  console.log("2. Spawning Thomas Edison...");
  const resEdison = await cmd({ type: "createCampaignNode", name: "Thomas Edison", kind: "agent", x: -200, y: 0 });
  currentTick = resEdison.worldState.tick;
  
  console.log("3. Spawning Nikola Tesla...");
  const resTesla = await cmd({ type: "createCampaignNode", name: "Nikola Tesla", kind: "agent", x: 200, y: 0 });
  currentTick = resTesla.worldState.tick;
  
  console.log("4. Spawning War of the Currents Front...");
  const resFront = await cmd({ type: "createCampaignNode", name: "War of the Currents", kind: "front", x: 0, y: -200 });
  const frontNode = resFront.worldState.campaignNodes[resFront.worldState.campaignNodes.length - 1];
  currentTick = resFront.worldState.tick;

  console.log("5. Injecting Event...");
  const injectRes = await cmd({
    type: "injectEvent",
    event: { 
      description: "Edison electrically executes an elephant using AC power to demonstrate its lethal danger.",
      sourceId: frontNode.id
    }
  });
  currentTick = injectRes.worldState.tick;
  console.log("Event Injected successfully at tick", currentTick);

  console.log("6. Fast forwarding 2 ticks to resolve consequence proposals API...");
  const ffRes = await cmd({ type: "fastForward", ticks: 2, aiSettings: { consequenceGeneration: true } });
  
  console.log("========= TEST COMPLETE =========");
  console.log("Latest Events Generated by Engine:");
  ffRes.worldState.events.slice(-5).forEach((e: any) => {
    console.log(`- [Tick ${e.tick}] [${e.type}] ${e.description}`);
  });
}

run().catch(err => {
  console.error("TEST FAILED:", err);
  process.exit(1);
});
